# Generated by Django 4.1.3 on 2022-11-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school_system_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="course_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="school_system_app.courses",
            ),
        ),
    ]
